name: linkchecker

services:
  checker:
    build: .
    ports:
      - 4321:4321
      - 1234:1234
  storage:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: somesecurepassword
      POSTGRES_DB: routerdata